[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages
unsafe_allow_html = false

# Process and display mathematical expressions
latex = false

# Automatically tag threads with the current chat profile
auto_tag_thread = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 10
    max_size_mb = 100

[features.speech_to_text]
    enabled = false

[UI]
# Name of the app and chatbot
name = "Smart Microgrid AI"

# Show the readme while the thread is empty
show_readme_as_default = true

# Default collapse content
default_collapse_content = true

# Default expand messages
default_expand_messages = false

# Hide the chain of thought details
hide_cot = false

[UI.theme]
[UI.theme.light]
    [UI.theme.light.primary]
        main = "#1976d2"

[UI.theme.dark]
    [UI.theme.dark.primary]
        main = "#1976d2"

[meta]
generated_by = "1.3.0"
